CREATE DATABASE IF NOT EXISTS lab7;
USE lab7;

CREATE TABLE IF NOT EXISTS Courses (
    CRN INT(11) NOT NULL PRIMARY KEY,
    Prefix VARCHAR(4) NOT NULL,
    Number SMALLINT(4) NOT NULL,
    Title VARCHAR(255) NOT NULL
);