CREATE DATABASE IF NOT EXISTS lab7;
USE lab7;

CREATE TABLE IF NOT EXISTS Students (
    RIN INT NOT NULL PRIMARY KEY,
    RCSID CHAR(7),
    FirstName VARCHAR(100) NOT NULL,
    LastName VARCHAR(100) NOT NULL,
    Alias VARCHAR(100) NOT NULL,
    Phone INT(15)
);